const GLOBAL_TIER_LIST = [
	"Blind Burrows",
	"Champion's Demise",
	"Earthen Wound",
	"Renegade's Retreat",
	"Sunken Ruins",
	"Aldurwood",
	"Guulrahn Canals",
	"Kor Dragan Baracks",
	"Maugan's Works",
	"Maulwood",
	"Raethwind Wilds",
	"Serpent's Lair",
	"Ancient's Lament",
	"Crusaders' Cathedral",
	"Dark Ravine",
	"The Onyx Hold",
	"Shivta Ruins",
	"Witchwater",
	"Abandoned Mineworks",
	"Cultist Refuge",
	"Demon's Wake",
	"Lost Archives",
	"Prison of Caldeum",
	"Whispering Pines",
	"Zenith",
	"Ferals' Den",
	"Guulrahn Slums",
	"Shadowed Plunge",
	"Conclave",
	"Black Asylum"
]

const GLOBAL_TIER_LIST_XP = [
	"Blind Burrows",
	"Guulrahn Canals",
	"Sunken Ruins",
	"Aldurwood",
	"Raethwind Wilds",
	"Maulwood",
	"Champion's Demise",
	"Demon's Wake",
	"Whispering Pines",
	"Lost Archives",
	"Witchwater",
	"Kor Dragan Baracks",
	"Ancient's Lament",
	"Earthen Wound",
	"Zenith",
	"Abandoned Mineworks",
	"The Onyx Hold",
	"Shadowed Plunge",
	"Renegade's Retreat",
	"Cultist Refuge",
	"Dark Ravine",
	"Serpent's Lair",
	"Black Asylum",
	"Guulrahn Slums",
	"Conclave",
	"Maugan's Works",
	"Shivta Ruins",
	"Ferals' Den",
	"Crusaders' Cathedral",
	"Prison of Caldeum"
]

const GLOBAL_TIER_LIST_GLYPH = [
	"Guulrahn Canals",
	"Aldurwood",
	"Maulwood",
	"Witchwater",
	"Raethwind Wilds",
	"Blind Burrows",
	"Sunken Ruins",
	"Cultist Refuge",
	"Lost Archives",
	"Maugan's Works",
	"Earthen Wound",
	"Shivta Ruins",
	"Serpent's Lair",
	"Crusaders' Cathedral",
	"Guulrahn Slums",
	"Dark Ravine",
	"Demon's Wake",
	"Shadowed Plunge",
	"Zenith",
	"Renegade's Retreat",
	"Abandoned Mineworks",
	"Prison of Caldeum",
	"Whispering Pines",
	"Ancient's Lament",
	"Champion's Demise",
	"Ferals' Den",
	"The Onyx Hold",
	"Kor Dragan Baracks",
	"Conclave",
	"Black Asylum"
]

const GLOBAL_TIER_LIST_COMBINED = [
	"Guulrahn Canals",
	"Aldurwood",
	"Blind Burrows",
	"Maulwood",
	"Raethwind Wilds",
	"Sunken Ruins",
	"Witchwater",
	"Lost Archives",
	"Demon's Wake",
	"Earthen Wound",
	"Cultist Refuge",
	"Champion's Demise",
	"Whispering Pines",
	"Zenith",
	"Serpent's Lair",
	"Maugan's Works",
	"Shadowed Plunge",
	"Abandoned Mineworks",
	"Ancient's Lament",
	"Dark Ravine",
	"Guulrahn Slums",
	"Renegade's Retreat",
	"Shivta Ruins",
	"Kor Dragan Baracks",
	"Crusaders' Cathedral",
	"The Onyx Hold",
	"Prison of Caldeum",
	"Black Asylum",
	"Conclave",
	"Ferals' Den"
]

module.exports = {
	GLOBAL_TIER_LIST,
	GLOBAL_TIER_LIST_XP,
	GLOBAL_TIER_LIST_GLYPH,
	GLOBAL_TIER_LIST_COMBINED
};