const GLOBAL_TIER_LIST = [
	"Blind Burrows",
	"Champion's Demise",
	"Earthen Wound",
	"Renegade's Retreat",
	"Sunken Ruins",
	"Aldurwood",
	"Guulrahn Canals",
	"Kor Dragan Baracks",
	"Maugan's Works",
	"Maulwood",
	"Raethwind Wilds",
	"Serpent's Lair",
	"Ancient's Lament",
	"Crusaders' Cathedral",
	"Dark Ravine",
	"The Onyx Hold",
	"Shivta Ruins",
	"Witchwater",
	"Abandoned Mineworks",
	"Cultist Refuge",
	"Demon's Wake",
	"Lost Archives",
	"Prison of Caldeum",
	"Whispering Pines",
	"Zenith",
	"Ferals' Den",
	"Guulrahn Slums",
	"Shadowed Plunge",
	"Conclave",
	"Black Asylum"
]

const GLOBAL_TIER_LIST_XP = [
	"Blind Burrows",
	"Guulrahn Canals",
	"Sunken Ruins",
	"Aldurwood",
	"Raethwind Wilds",
	"Maulwood",
	"Champion's Demise",
	"Demon's Wake",
	"Whispering Pines",
	"Lost Archives",
	"Witchwater",
	"Kor Dragan Baracks",
	"Ancient's Lament",
	"Earthen Wound",
	"Zenith",
	"Abandoned Mineworks",
	"The Onyx Hold",
	"Shadowed Plunge",
	"Renegade's Retreat",
	"Cultist Refuge",
	"Dark Ravine",
	"Serpent's Lair",
	"Black Asylum",
	"Guulrahn Slums",
	"Conclave",
	"Maugan's Works",
	"Shivta Ruins",
	"Ferals' Den",
	"Crusaders' Cathedral",
	"Prison of Caldeum"
]

const GLOBAL_TIER_LIST_GLYPH = [
	"Guulrahn Canals",
	"Aldurwood",
	"Maulwood",
	"Witchwater",
	"Raethwind Wilds",
	"Blind Burrows",
	"Sunken Ruins",
	"Cultist Refuge",
	"Lost Archives",
	"Maugan's Works",
	"Earthen Wound",
	"Shivta Ruins",
	"Serpent's Lair",
	"Crusaders' Cathedral",
	"Guulrahn Slums",
	"Dark Ravine",
	"Demon's Wake",
	"Shadowed Plunge",
	"Zenith",
	"Renegade's Retreat",
	"Abandoned Mineworks",
	"Prison of Caldeum",
	"Whispering Pines",
	"Ancient's Lament",
	"Champion's Demise",
	"Ferals' Den",
	"The Onyx Hold",
	"Kor Dragan Baracks",
	"Conclave",
	"Black Asylum"
]

const GLOBAL_TIER_LIST_COMBINED = [
	"Guulrahn Canals",
	"Aldurwood",
	"Blind Burrows",
	"Maulwood",
	"Raethwind Wilds",
	"Sunken Ruins",
	"Witchwater",
	"Lost Archives",
	"Demon's Wake",
	"Earthen Wound",
	"Cultist Refuge",
	"Champion's Demise",
	"Whispering Pines",
	"Zenith",
	"Serpent's Lair",
	"Maugan's Works",
	"Shadowed Plunge",
	"Abandoned Mineworks",
	"Ancient's Lament",
	"Dark Ravine",
	"Guulrahn Slums",
	"Renegade's Retreat",
	"Shivta Ruins",
	"Kor Dragan Baracks",
	"Crusaders' Cathedral",
	"The Onyx Hold",
	"Prison of Caldeum",
	"Black Asylum",
	"Conclave",
	"Ferals' Den"
]

const GLOBAL_TIER_LIST_S1_XP = [
	"Uldur's Cave",
	"Sarat's Lair",
	"Mercy's Reach",
	"Dead Man's Dredge",
	"Norstrava",
	"Tomb of the Saints",
	"Komdor Temple",
	"Pallid Delve",
	"Hoarfrost Demise",
	"Akhan's Grasp",
	"Charnel House",
	"Immortal Emenation",
	"Ancient Reservoir",
	"Kor Valar Ramparts",
	"Stockades",
	"Mariner's refuge",
	"Garan Hold",
	"Twisted Hollow",
	"Shifting City",
	"Domhainne Tunnel",
	"Iron Hold",
	"Collapsed Vault",
	"Betrayer's Row",
	"Faceless Shrine",
	"Lost Keep",
	"Heretics Asylum",
	"Path of the Blind",
	"Forgotten Ruins",
	"Bastion of Faith",
	"Halls of the Damned"
]

const GLOBAL_TIER_LIST_S1_GLYPH = [
	"Sarat's Lair",
	"Uldur's Cave",
	"Hoarfrost Demise",
	"Mercy's Reach",
	"Norstrava",
	"Dead Man's Dredge",
	"Iron Hold",
	"Komdor Temple",
	"Ancient Reservoir",
	"Bastion of Faith",
	"Pallid Delve",
	"Kor Valar Ramparts",
	"Domhainne Tunnel",
	"Shifting City",
	"Faceless Shrine",
	"Tomb of the Saints",
	"Twisted Hollow",
	"Path of the Blind",
	"Collapsed Vault",
	"Stockades",
	"Charnel House",
	"Garan Hold",
	"Akhan's Grasp",
	"Heretics Asylum",
	"Immortal Emenation",
	"Lost Keep",
	"Mariner's refuge",
	"Betrayer's Row",
	"Halls of the Damned",
	"Forgotten Ruins"
]

const GLOBAL_TIER_LIST_S1_COMBINED = [
	"Sarat's Lair",
	"Uldur's Cave",
	"Mercy's Reach",
	"Dead Man's Dredge",
	"Norstrava",
	"Hoarfrost Demise",
	"Komdor Temple",
	"Pallid Delve",
	"Ancient Reservoir",
	"Tomb of the Saints",
	"Kor Valar Ramparts",
	"Iron Hold",
	"Charnel House",
	"Akhan's Grasp",
	"Domhainne Tunnel",
	"Shifting City",
	"Stockades",
	"Twisted Hollow",
	"Immortal Emenation",
	"Bastion of Faith",
	"Faceless Shrine",
	"Garan Hold",
	"Collapsed Vault",
	"Mariner's refuge",
	"Path of the Blind",
	"Heretics Asylum",
	"Betrayer's Row",
	"Lost Keep",
	"Forgotten Ruins",
	"Halls of the Damned"
]

const GLOBAL_TIER_LIST_EVENT = [
	"Last stand",
	"Cursed Chest",
	"Cursed Well",
	"Wandering Soul",
	"Ritual of Blood"
]

// Patch 1.1.1
const GLOBAL_TIER_LIST_S1_XP_v2 = [
	"Uldur's Cave",
	"Sarat's Lair",
	"Mariner's refuge",
	"Hoarfrost Demise",
	"Immortal Emenation",
	"Domhainne Tunnel",
	"Mercy's Reach",
	"Pallid Delve",
	"Tomb of the Saints",
	"Akhan's Grasp",
	"Charnel House",
	"Norstrava",
	"Dead Man's Dredge",
	"Forgotten Ruins",
	"Komdor Temple",
	"Ancient Reservoir",
	"Collapsed Vault",
	"Garan Hold",
	"Stockades",
	"Lost Keep",
	"Twisted Hollow",
	"Iron Hold",
	"Betrayer's Row",
	"Kor Valar Ramparts",
	"Bastion of Faith",
	"Shifting City",
	"Faceless Shrine",
	"Heretics Asylum",
	"Path of the Blind",
	"Halls of the Damned"
]

// Patch 1.1.1
const GLOBAL_TIER_LIST_S1_GLYPH_v2 = [
	"Hoarfrost Demise",
	"Sarat's Lair",
	"Mariner's refuge",
	"Iron Hold",
	"Mercy's Reach",
	"Twisted Hollow",
	"Uldur's Cave",
	"Bastion of Faith",
	"Garan Hold",
	"Shifting City",
	"Immortal Emenation",
	"Domhainne Tunnel",
	"Norstrava",
	"Heretics Asylum",
	"Pallid Delve",
	"Collapsed Vault",
	"Komdor Temple",
	"Kor Valar Ramparts",
	"Stockades",
	"Ancient Reservoir",
	"Tomb of the Saints",
	"Dead Man's Dredge",
	"Faceless Shrine",
	"Path of the Blind",
	"Forgotten Ruins",
	"Charnel House",
	"Betrayer's Row",
	"Akhan's Grasp",
	"Lost Keep",
	"Halls of the Damned"
]

module.exports = {
	GLOBAL_TIER_LIST,
	GLOBAL_TIER_LIST_XP,
	GLOBAL_TIER_LIST_GLYPH,
	GLOBAL_TIER_LIST_COMBINED,
	GLOBAL_TIER_LIST_S1_XP,
	GLOBAL_TIER_LIST_S1_GLYPH,
	GLOBAL_TIER_LIST_S1_COMBINED,
	GLOBAL_TIER_LIST_EVENT,
	GLOBAL_TIER_LIST_S1_XP_v2,
	GLOBAL_TIER_LIST_S1_GLYPH_v2
};